const data = [
  {
    id: 1,
    title: "Puma One 2 FG",
    category: "football",
    price: 6299,
    img: "https://th.bing.com/th/id/OIP.Tbo5tE5ulHrGATZBDtwpCgHaHa?w=176&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `PUMA ONE 2 FG Leather football boots for men has a mix of bladed and conical studs, and is suitable for use on firm ground `,
  },
  {
    id: 2,
    title: "Puma Mens Court Rider 2.0 Basketball Shoe",
    category: "basketball",
    price: 6999,
    img: "https://cdn.shopify.com/s/files/1/0180/4854/8964/products/PUM_19565801_01B_01.jpg?v=1617731475",
    desc: `Style: These unisex Basketball shoes have a colorful pattern.
      Comfort: The lace-up feature ensures that your feet have a perfect fit. `,
  },
  {
    id: 3,
    title: "Adidas Crazyquick 2.0 Mens Football ",
    category: "football",
    price: 3481,
    img: "https://th.bing.com/th/id/OIP.S8qdOHOyXB2AH1eWTA6tbwHaE9?w=263&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `Adidas Crazyquick 2.0 Mens Football boots Padded Footbed::Plastic Studs on Sole::Textured Footbed::Textured Sole, and is suitable for use on firm ground.`,
  },
  {
    id: 4,
    title: "Adidas Unisex-Adult Harden Stepback 3 Basketball Shoe",
    category: "basketball",
    price: 7200,
    img: "https://m.media-amazon.com/images/I/81WWsIATEjL._UX695_.jpg",
    desc: ` These unisex Basketball shoes have a colorful pattern Closure: Lace-Up
      Fit Type: Regular `,
  },
  {
    id: 5,
    title: "Jordan 9 Retro",
    category: "basketball",
    price: 33033,
    img: "https://th.bing.com/th/id/OIP.tk9Hglt7AzxOEFRGR_EFnAHaE8?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    desc: `Debuting back in 1993, the Air Jordan 9 was the one sneaker to release during Michael Jordan’s 13-month stint in Minor League Baseball.  `,
  },
  {
    id: 6,
    title: "Nike Air Zoom Mercurial Superfly 9 ",
    category: "football",
    price: 22062,
    img: "https://i.pinimg.com/originals/3c/9d/3c/3c9d3cc34cf8407b5ec46dab37e22425.png",
    desc: `The Air Zoom Mercurial's new Tri-Star stud design powers both lateral and downhill movement for faster play in all directions.`,
  },
  {
    id: 7,
    title: "Adidas Vector Mid  Cricket Spikes",
    category: "cricket",
    price: 11014,
    img: "https://images.prodirectsport.com/ProductImages/Gallery_2/233520_Gallery_2_0849237.jpg",
    desc: `Lock down your feet so you can shut down batsmen with adidas Vector Mid Cricket spikes in featuring a new BOA lacing system for the ultimate secure fit `,
  },
  {
    id: 8,
    title: " Payntr XPF-AR All-Rounder Spike",
    category: "cricket",
    price: 11702,
    img: "https://payntr.com/images/xpf-ar-all-rounder-spike-adults-p151-729_image.jpg",
    desc: `The new XPF-AR All-Rounder Spike has been designed to give the complete all-rounder the ultimate performance. Based on a running last to provide a superior fit and feel `,
  },
  {
    id: 9,
    title: "Newbery’s unique CricSok",
    category: "cricket",
    price: 4425,
    img: "https://cdn.shopify.com/s/files/1/0364/1041/products/WhitewithGreenNSeriesLogospikesSide_1600x.png?v=1633621925",
    desc: `Newbery’s unique CricSok feature maximises natural motion & provides flexibility for moving quickly between the wickets or around the outfield.`,
  },
];
export default data;
